# Generated by Django 3.0.3 on 2020-02-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20200226_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userapps', to='app_one.Image'),
        ),
    ]
