# Generated by Django 3.0.3 on 2020-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_userapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
