# Generated by Django 3.0.3 on 2020-02-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20200227_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial_row',
            field=models.BooleanField(default=True),
        ),
    ]
