# Generated by Django 3.0.3 on 2020-03-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='url',
        ),
        migrations.AddField(
            model_name='userapp',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
